name: '[CI] React Native'

on:
  push:
    branches:
      - main
      - vr/fix-workflow
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: flyci-macos-14-m2
    steps:
      - uses: actions/checkout@v3

      - name: Check xcode-select --version
        run: xcode-select --version

      - name: Install Bundle
        run: bundle install

      - name: Install node modules
        run: yarn install

      - name: Install pods
        run: cd ios && bundle exec pod install

      #   - name: Build iOS
      #     run: npx react-native build-ios

      - name: Build with XCode
        run: xcodebuild -workspace FlyCIReactNativeApp.xcworkspace -configuration Debug -scheme FlyCIReactNativeApp -destination generic/platform=iOS Simulator
